# -*- coding: utf-8 -*-
"""从 PE 里按虚拟地址导出数据（PT00.dll 的动画帧表取证用）。

PT00.dll 的动画表是「增量表 + 前缀和」：运行时用
`sub_100022D0(dst, src, count)` 把 src 的 count 个 dword 做前缀和写进 dst，
所以 `.data` 里存的是增量，运行期才变成帧阈值。

用法（三种模式）：
    1) 交互式区间导出（保留）：
        python tools/dump_tables.py <dll> --range 0x1001F040 0x1001F210
        python tools/dump_tables.py <dll> 0x1001F128 0x1001F164 ...

    2) 声明式清单 + 生成器（可复现 / 可重跑 / 可审查，推荐）：
        python tools/dump_tables.py --manifest tools/pt00_tables.json \
            --dll <PT00.dll> --out generated/pt00_tables.inc

清单（tools/pt00_tables.json）每张表：
    { "name": "kXxxTable",                  # 生成的 C++ 数组名
      "address": "0x1001F040",              # 表起始 VA
      "count": 116,                          # 固定条目数；或
      "count_from": "0x1001F0AC",            # 条目数所在全局 dword 的 VA（先读该地址 uint32）
      "element": "uint32_t",                 # 元素类型（默认 uint32_t）
      "comment": "..." }

生成器对每张表显式回报：名称 / 地址 / 条目数来源（固定或读全局的实读值）/ 字节数，
任一步失败即报错并 exit != 0（禁止静默跳过）。

只依赖标准库。每行给出 地址 / 十进制 / 十六进制，方便直接抄进 C++。
"""

import io
import json
import os
import struct
import sys

MAX_COUNT = 1 << 20  # 单表条目数保护上限（防 count_from 读错导致巨分配）


def parse_pe(data):
    e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    if data[e_lfanew:e_lfanew + 4] != b"PE\0\0":
        raise ValueError("not a PE file")
    nsec = struct.unpack_from("<H", data, e_lfanew + 6)[0]
    size_opt = struct.unpack_from("<H", data, e_lfanew + 20)[0]
    opt = e_lfanew + 24
    image_base = struct.unpack_from("<I", data, opt + 28)[0]
    st = opt + size_opt
    sections = []
    for i in range(nsec):
        off = st + i * 40
        name = data[off:off + 8].rstrip(b"\0").decode("latin1")
        vsize, vaddr, rawsize, rawptr = struct.unpack_from("<IIII", data, off + 8)
        sections.append((name, vaddr, vsize, rawptr, rawsize))
    return image_base, sections


def read_va(data, image_base, sections, va, nbytes):
    rva = va - image_base
    for _name, vaddr, vsize, rawptr, rawsize in sections:
        if vaddr <= rva < vaddr + max(vsize, rawsize):
            start = rawptr + (rva - vaddr)
            end = start + nbytes
            if end > len(data):
                raise ValueError("VA %s 读 %d 字节越界（文件长度 %d）" % (hex(va), nbytes, len(data)))
            return data[start:end]
    raise KeyError("VA 不在任何段里（可能是 BSS，运行期才有值）: %s" % hex(va))


def parse_int(s):
    """'0x...' 十六进制 / 十进制 字符串 → int。"""
    if isinstance(s, int):
        return s
    t = str(s).strip()
    return int(t, 16) if t.lower().startswith("0x") else int(t)


def emit_array(lines, table, vals, count):
    """把一张表写进 .inc 文本行列表。"""
    name = table["name"]
    count_name = table.get("count_name", name + "Count")
    element = table.get("element", "uint32_t")
    count_src = "固定值 %d" % count
    if "count_from" in table:
        count_src = "读全局 %s（实读 %d）" % (table["count_from"], count)
    lines.append("")
    lines.append("// ---------------------------------------------------------------")
    lines.append("// %s @ VA %s（条目数 %s）" % (name, table["address"], count_src))
    if table.get("comment"):
        lines.append("// %s" % table["comment"])
    lines.append("// ---------------------------------------------------------------")
    lines.append("const %s %s[] = {" % (element, name))
    per_row = 8
    for i in range(0, count, per_row):
        row = ", ".join("0x%08X" % v for v in vals[i:i + per_row])
        lines.append("    %s," % row)
    lines.append("};")
    lines.append("constexpr size_t %s = %d;" % (count_name, count))
    lines.append("")


def generate_manifest(data, image_base, sections, manifest_path, out_path):
    with io.open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    tables = manifest.get("tables", [])
    if not tables:
        raise ValueError("清单 %s 里没有 tables 项" % manifest_path)

    lines = [
        "// Auto-generated by tools/dump_tables.py --manifest %s --dll %s --out %s"
        % (os.path.basename(manifest_path), manifest.get("source_dll", "PT00.dll"), os.path.basename(out_path)),
        "// Source: %s（image base %s）" % (manifest.get("source_dll", "PT00.dll"), manifest.get("image_base", hex(image_base))),
        "// DO NOT EDIT：重新提取请重跑上方命令（清单 = 单一事实来源，可审查）。",
        "#pragma once",
        "#include <cstddef>",
    ]

    for table in tables:
        name = table.get("name")
        if not name:
            raise ValueError("清单里存在缺少 name 的表项：%r" % table)
        va = parse_int(table["address"])
        # 条目数：固定值 或 读全局 dword
        if "count" in table and "count_from" in table:
            raise ValueError("表 %s 同时给了 count 与 count_from（二选一）" % name)
        if "count" in table:
            count = parse_int(table["count"])
            count_src = "fixed:%d" % count
        elif "count_from" in table:
            cf = parse_int(table["count_from"])
            raw = read_va(data, image_base, sections, cf, 4)
            count = struct.unpack("<I", raw)[0]
            count_src = "global:%s=%d" % (table["count_from"], count)
        else:
            raise ValueError("表 %s 缺 count 或 count_from" % name)
        if count <= 0:
            raise ValueError("表 %s 条目数无效（%d）" % (name, count))
        if count > MAX_COUNT:
            raise ValueError("表 %s 条目数 %d 超过保护上限 %d（请检查 count_from 是否读对）"
                             % (name, count, MAX_COUNT))
        raw = read_va(data, image_base, sections, va, count * 4)
        vals = struct.unpack("<%dI" % count, raw)
        emit_array(lines, table, vals, count)
        # 显式回报（禁止静默）
        print("  [ok] %-28s @ %-12s %s（%d 项 / %d 字节）"
              % (name, table["address"], count_src, count, count * 4))

    with io.open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return len(tables)


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return

    # 模式 2：声明式清单 + 生成器
    if "--manifest" in args:
        if "--dll" not in args or "--out" not in args:
            print("用法：python tools/dump_tables.py --manifest <清单.json> --dll <PT00.dll> --out <输出.inc>",
                  file=sys.stderr)
            sys.exit(1)
        manifest_path = args[args.index("--manifest") + 1]
        dll_path = args[args.index("--dll") + 1]
        out_path = args[args.index("--out") + 1]
        data = open(dll_path, "rb").read()
        image_base, sections = parse_pe(data)
        os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
        print("清单 %s → %s（%d 张表）" % (manifest_path, out_path,
                                         len(json.load(open(manifest_path, encoding="utf-8")).get("tables", []))))
        n = generate_manifest(data, image_base, sections, manifest_path, out_path)
        print("完成：%d 张表写入 %s" % (n, out_path))
        return

    # 模式 1：交互式区间导出（保留）
    args = sys.argv[2:]
    if not args:
        print(__doc__)
        return
    data = open(sys.argv[1], "rb").read()
    image_base, sections = parse_pe(data)

    ranges = []
    if args[0] == "--range":
        start, end = int(args[1], 16), int(args[2], 16)
        ranges.append((start, end))
    else:
        for a in args:
            va = int(a, 16)
            ranges.append((va, va + 4))

    for start, end in ranges:
        count = (end - start) // 4
        raw = read_va(data, image_base, sections, start, count * 4)
        print("== %s .. %s (%d dwords) ==" % (hex(start), hex(end), count))
        vals = struct.unpack("<%dI" % count, raw)
        for i, v in enumerate(vals):
            as_signed = struct.unpack("<i", struct.pack("<I", v))[0]
            print("  %s  %-12d  0x%08X" % (hex(start + i * 4), as_signed, v))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, OSError, json.JSONDecodeError) as e:
        print("错误：%s" % e, file=sys.stderr)
        sys.exit(1)
